### ISSUE TITLE
error

### ISSUE THREAD

**Issue by useragent23253** [naksyn/Pyramid#5]
python3 PyramidHTTP.py 443 user Password@123 /root/home/user/SSL/key.pem /root/home/user/SSL/cert.pem /root/home/user/Pyramid/Server/

__________                              .__    .___
\______   \___.__.____________    _____ |__| __| _/
 |     ___<   |  |\_  __ \__  \  /     \|  |/ __ | 
 |    |    \___  | |  | \// __ \|  Y Y  \  / /_/ | 
 |____|    / ____| |__|  (____  /__|_|  /__\____ | 
           \/                 \/      \/        \/
 
 HTTP/S server with Basic Auth                    
           
[+] Pyramid HTTP Server listening on port  443
[+] Serving Pyramid files from folder  /root/home/user/Pyramid/Server/
[+] Using SSL key  /root/home/user/SSL/key.pem
[+] Using SSL cert  /root/home/user/SSL/cert.pem
[+] User allowed to fetch files:  user
[!] ENTER PEM PASSPHRASE BELOW AND PRESS ENTER
Traceback (most recent call last):
  File "PyramidHTTP.py", line 190, in <module>
    server.socket = ssl.wrap_socket (server.socket, options.sslkey, options.sslcert, server_side=True)
  File "/usr/lib/python3.7/ssl.py", line 1216, in wrap_socket
    context.load_cert_chain(certfile, keyfile)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by naksyn** [comment]
Hi, looks like the certfile and keyfile are not found. Did you create the files with a command like: 
`openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365` and made sure that paths are correct?

**Comment by useragent23253** [comment]
forgot upgrade after installation, working
