### ISSUE TITLE
socks disconnecting

### ISSUE THREAD

**Issue by avg-socks-enjoyer** [naksyn/Pyramid#6]
Hi. Could you help me please.
I testing your scripts and found that socks5 tunnel just dropping after few hours of connection. On testing machine there's no problem with process, all works. netstat -an shows ssh connection established, but at server process sshd just dying after some time. I tried to edit flags at source of .py file, added keep interval at server, tcp alive and etc but nothing helped me. Confused with this.

**Comment by naksyn** [comment]
Hi, the script does not implement any keepalive and by default paramiko [sets it to off](https://docs.paramiko.org/en/stable/api/transport.html)
Keeping SSH up for hours might require to set keepalive on both client and server. 
Client-side, you could add **set_keepalive(interval)** in the Pyramid script, and tune the server ssh config like in this [post](https://patrickmn.com/aside/how-to-keep-alive-ssh-sessions/).
Let me know if this helped

**Comment by avg-socks-enjoyer** [comment]
Thx, got it.
I will try it now and will see if it's will die. Will answer later. 

Also thx for project :D

**Comment by naksyn** [comment]
No problem! glad you like the project

**Comment by avg-socks-enjoyer** [comment]
It works for 14 hours now, so i think it will work. I will close it, TY for help!
